### ISSUE TITLE
Divergence error for sliding mesh simulations

### ISSUE THREAD

**Issue by SumanVajjala** [su2code/SU2#401]
Hi. I have successfully run the sliding mesh test case for rotating cylinders. However, when I change the simulation type to Navier-Stokes in the cfg file the solution diverges before starting the CFD iterations. Can you please suggest what is going wrong and how to avoid this error.

Regards
Suman Vajjala

**Comment by LaSerpe** [comment]
Hi Suman,
which branch of SU2 are you using?

If you are using the master, I suggest switching to the develop branch.
The sliding mesh feature is a pretty new addition to the code, so you may be facing some issues that we already solved in the develop branch.

Cheers,
Giulio Gori

**Comment by SumanVajjala** [comment]
Hi Guilo,
I am using v5.0.0 downloaded from github. I do not use git to update my repository. So, I will download the develop branch and check if the issue is resolved. Many thanks for your reply and congrats for developing such extremely useful models!

Regards
Suman Vajjala

**Comment by SumanVajjala** [comment]
Hi Guilio,
I have downloaded and installed the develop branch version but I am still getting the same error. I am attaching the config file for your reference. I hope I am using the correct cfg file.

Thanks and regards
Suman Vajjala
[twoprop.su2.gz](https://github.com/su2code/SU2/files/1067875/twoprop.su2.gz)
[rot_prop_NN.cfg.gz](https://github.com/su2code/SU2/files/1067877/rot_prop_NN.cfg.gz)

**Comment by LaSerpe** [comment]
Hi Suman,
Regarding your config file: first you have to specify the turbulence model you would like to use (your config reads NONE right now), secondly you have to add the parameters for the computation of turbulent fluxes.
In this latter case I suggest you to have a look at one of the test cases in the "rans" folder.
This made your case working on my laptop, if you encounter any other issue don't hesitate to ask me.

Cheers,
Giulio

**Comment by SumanVajjala** [comment]
Hi Guilio,
Thank you for your help! We figured out that by experimenting! I was wondering why we cant run the same for a case without any turbulence models as in a direct simulation or a laminar simulation. 

Best regards
Suman
